# fly.toml app configuration file generated for tobias-bot on 2023-05-14T19:25:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tobias-bot"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
